on:
  workflow_dispatch:
  push:
    branches: [main]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.16

      - name: Quarto check
        run: quarto check
      
      - name: Set up D2
        run: curl -fsSL https://d2lang.com/install.sh | sh -s -- --version="v0.6.0" --method=standalone --prefix="$(pwd)/.local"

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: docs
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
